/*
 * Copyright (c) 2019 Manulytica Ltd 
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _MANULYTICA_HEALTH_FAULTS_H_
#define _MANULYTICA_HEALTH_FAULTS_H_


#define HEALTH_FAULT_ID_NO_FAULT   0x00
#define HEALTH_FAULT_ID_BATTERY_LOW_WARNING   0x01
#define HEALTH_FAULT_ID_BATTERY_LOW_ERROR   0x02
#define HEALTH_FAULT_ID_SUPPLY_VOLTAGE_LOW_WARNING   0x03
#define HEALTH_FAULT_ID_SUPPLY_VOLTAGE_LOW_ERROR   0x04
#define HEALTH_FAULT_ID_SUPPLY_VOLTAGE_HIGH_WARNING   0x05
#define HEALTH_FAULT_ID_SUPPLY_VOLTAGE_HIGH_ERROR   0x06
#define HEALTH_FAULT_ID_POWER_SUPPLY_INTERRUPTED_WARNING   0x07
#define HEALTH_FAULT_ID_POWER_SUPPLY_INTERRUPTED_ERROR   0x08
#define HEALTH_FAULT_ID_NO_LOAD_WARNING   0x09
#define HEALTH_FAULT_ID_NO_LOAD_ERROR   0x0a
#define HEALTH_FAULT_ID_OVERLOAD_WARNING   0x0b
#define HEALTH_FAULT_ID_OVERLOAD_ERROR   0x0c
#define HEALTH_FAULT_ID_OVERHEAT_WARNING   0x0d
#define HEALTH_FAULT_ID_OVERHEAT_ERROR   0x0e
#define HEALTH_FAULT_ID_CONDENSATION_WARNING   0x0f
#define HEALTH_FAULT_ID_CONDENSATION_ERROR   0x10
#define HEALTH_FAULT_ID_VIBRATION_WARNING   0x11
#define HEALTH_FAULT_ID_VIBRATION_ERROR   0x12
#define HEALTH_FAULT_ID_CONFIGURATION_WARNING   0x13
#define HEALTH_FAULT_ID_CONFIGURATION_ERROR   0x14
#define HEALTH_FAULT_ID_ELEMENT_NOT_CALIBRATED_WARNING   0x15
#define HEALTH_FAULT_ID_ELEMENT_NOT_CALIBRATED_ERROR   0x16
#define HEALTH_FAULT_ID_MEMORY_WARNING   0x17
#define HEALTH_FAULT_ID_MEMORY_ERROR   0x18
#define HEALTH_FAULT_ID_SELFTEST_WARNING   0x19
#define HEALTH_FAULT_ID_SELFTEST_ERROR   0x1a
#define HEALTH_FAULT_ID_INPUT_TOO_LOW_WARNING   0x1b
#define HEALTH_FAULT_ID_INPUT_TOO_LOW_ERROR   0x1c
#define HEALTH_FAULT_ID_INPUT_TOO_HIGH_WARNING   0x1d
#define HEALTH_FAULT_ID_INPUT_TOO_HIGH_ERROR   0x1e
#define HEALTH_FAULT_ID_INPUT_NO_CHANGE_WARNING   0x1f
#define HEALTH_FAULT_ID_INPUT_NO_CHANGE_ERROR   0x20
#define HEALTH_FAULT_ID_ACTUATOR_BLOCKED_WARNING   0x21
#define HEALTH_FAULT_ID_ACTUATOR_BLOCKED_ERROR   0x22
#define HEALTH_FAULT_ID_HOUSING_OPENED_WARNING   0x23
#define HEALTH_FAULT_ID_HOUSING_OPENED_ERROR   0x24
#define HEALTH_FAULT_ID_TAMPER_WARNING   0x25
#define HEALTH_FAULT_ID_TAMPER_ERROR   0x26
#define HEALTH_FAULT_ID_DEVICE_MOVED_WARNING   0x27
#define HEALTH_FAULT_ID_DEVICE_MOVED_ERROR   0x28
#define HEALTH_FAULT_ID_DEVICE_DROPPED_WARNING   0x29
#define HEALTH_FAULT_ID_DEVICE_DROPPED_ERROR   0x2a
#define HEALTH_FAULT_ID_OVERFLOW_WARNING   0x2b
#define HEALTH_FAULT_ID_OVERFLOW_ERROR   0x2c
#define HEALTH_FAULT_ID_EMPTY_WARNING   0x2d
#define HEALTH_FAULT_ID_EMPTY_ERROR   0x2e
#define HEALTH_FAULT_ID_INTERNAL_BUS_WARNING   0x2f
#define HEALTH_FAULT_ID_INTERNAL_BUS_ERROR   0x30
#define HEALTH_FAULT_ID_MECHANISM_JAMMED_WARNING   0x31
#define HEALTH_FAULT_ID_MECHANISM_JAMMED_ERROR   0x32

/* 0x80–0xFF Vendor Specific Warnings / Errors */
#define HEALTH_FAULT_ID_VENDOR_START   0x80

/* End of Define trap */
#endif